// Tiny dependency-free PDF writer used ONLY for demo mode downloads.
// In normal mode, PDFs are generated by the backend (PDFKit) and downloaded from /api/reports/:id/download.
const esc = (s) =>
  String(s)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7E]/g, '?');

function wrap(line, max = 92) {
  const out = [];
  let cur = '';
  for (const w of String(line).split(' ')) {
    if ((cur + ' ' + w).trim().length > max) {
      out.push(cur);
      cur = w;
    } else cur = (cur + ' ' + w).trim();
  }
  out.push(cur);
  return out;
}

export function makePdfBlob(title, lines) {
  const all = [];
  lines.forEach((l) => (l === '' ? all.push('') : wrap(l).forEach((x) => all.push(x))));
  const perPage = 48;
  const pages = [];
  for (let i = 0; i < all.length; i += perPage) pages.push(all.slice(i, i + perPage));
  if (!pages.length) pages.push([]);

  const objs = [];
  const add = (s) => {
    objs.push(s);
    return objs.length;
  };
  add('<< /Type /Catalog /Pages 2 0 R >>');
  add('PLACEHOLDER');
  const font = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const bold = add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const pageIds = [];
  pages.forEach((pg, idx) => {
    let s = 'BT\n';
    if (idx === 0) s += `/F2 16 Tf 56 790 Td (${esc(title)}) Tj\n/F1 10 Tf 0 -26 Td\n`;
    else s += '/F1 10 Tf 56 790 Td\n';
    pg.forEach((l) => {
      s += `(${esc(l)}) Tj 0 -14 Td\n`;
    });
    s += 'ET\n';
    s += `BT /F1 8 Tf 280 24 Td (Page ${idx + 1} of ${pages.length}) Tj ET\n`;
    const c = add(`<< /Length ${s.length} >>\nstream\n${s}endstream`);
    const p = add(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents ${c} 0 R /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> >>`
    );
    pageIds.push(p);
  });
  objs[1] = `<< /Type /Pages /Kids [${pageIds.map((i) => `${i} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;

  let pdf = '%PDF-1.4\n';
  const offsets = [];
  objs.forEach((o, i) => {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => {
    pdf += String(o).padStart(10, '0') + ' 00000 n \n';
  });
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([pdf], { type: 'application/pdf' });
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
